---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgB9jKqiTx1Rbzt9Kd3tkdaNR+Q+Wv8hDS804bqzJYR/lsI3ebJXMCd/KKTcUdoPchPg5N1KvV7BcbIPou/PICAVBtgOKc4vZH1m9WKaFljbwndJXDEiwpFNB4lyFoVOzk0brNyx8fRu+Ca0tkv2qkDriC2zjYHkYrEz6gZQM2XQLU+qU+GxAWbgV7oobqukP9MC7C2NUNIJy+1+JlD7OHbProYE9p8+q2XH1ezX593Xfi+CKq/sx79UNDx4lXHJq1w3fbaHwSaY35zpYDaCAE8t7Y/BVu+bMYFvI8ujy0FT3fsp1U9Rye0cxLwFfDSFsDNzlT92YHigyf8fFe+a5tZMBT0egag79G4G1lXz2OWo6YlIsM/7SYDXRBKtZu1cwhr5FuJWRgHOjcvNQqfQ2hxPd0w8AFvYsdmXnvQ1OgjsHiGzB6JJuO+/NNcBDjEoz1gzDteb9YB7N0WTeew86D0IHBNqlcI4L3w46R7y2xBk6nnuHqifhhOLR6XDAM0iBvFf7Q+L230yyB585P6WJH8viMVSh/US5bWBWLJQ8tQ+jtr+PJVZexkmz3oFR54W155npv3BlHdDHQr1M/SnCVLjTxvg8gV8AJ+BThxiOZ5Rj2F7X8/+Q76RRvTf8Eub7IcsBE6VvAW6X2v6N/+Q9pOrXstjLtA7vhup7hyvlA4ggY42G8HNCpIh94p24MuOwmalj5Gbl7CLlA==
    username: AgACXA3I9Ux48xpLTqdMANImglGudmmPUNTojnar031VXwbhcBXpBVx+m3PYFypahZboGLmSGl10278o0kesFXILZ8pFz/7cvbedSGzgt+l1K0BlWHNpqe/rRdu0kYa6I7TGjKIkmhgLOsz1JKuat6vyjzd2Y2lqyZvusAPqMDA9Yb6vO6NaAqWmAWuXylf2+ImVHV0tNPaty8UMkeX8LkyPW8b+GDHRNUDnLXzFgBzZnkDEAkh/E+KVF7fKCvDk/o5WvahTdrg+yN9Z5B5V+2Oqt4RA6ETkCgKEuFgLPWwSUaFqf6pF/2fREEo1cGp+zd9SeR5twi6Knt6yJdcwXtP1SvpicDXG/X4LUL9ngX1cHMVPJCNX9WZ2U/4dVJgHqWZsj/LK3oQwXBTs5cSoqAOSvmkM9T/M/PvNebekzyo2+xv4Z/x06+rkYpyi7LWT22qgupJ3AFHhFpU55SRMhx5xirbmT4hF1Tg7kfHfHNKRpqdvI5o5QvufMscMExqhcZQkgFMJK2ZmtB2iPCvZf8dLTvnigRH9XK2LoJZhwKjiZXb+hb2Zsk3qrAP0trq+bDT9hQXPpVOJCKVL/+RdFJwCyx6Z1w0TmkXz5AqtYGIQqon8qQxy07kjxUHu5p3nXZkKIeWSiprCx7uXNPyzuCURa773e3N0Sjnl/jdicjen9KlAgczUeRwHWFOB60bNLVTQs4frJQ==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque
